### ISSUE TITLE
Trying to drop STAT_LINK col that doesn't exist

### ISSUE THREAD

**Issue by EStickland** [Err0neus/Project_Santos#49]
Getting an error in get_discogs.py:

_/Documents/Git/Project_Santos_Mar21/functions/get_discogs.py in get_album_stat(url, df)
    _274             df_stat_link.loc[df_stat_link["ARTIST_ID"] == row["ARTIST_ID"], "NUM_OF_PPL_WANT"] = _num_want.get_text()
    _275 
_--> 276     return df_stat_link.drop(['STAT_LINK'], axis=1)
    _277______ 

Getting the error on the latest pull and the an old version that used to work.

**Comment by Err0neus** [comment]
This seems to be due to changes on Discogs website.
Few changes observed:
a) now using HTTPS instead of HTTP, redirecting the HTTP urls to the HTTPS.
b) In addition, the URL now includes both artist id and name, as opposed to only artist id
i.e. 
FROM: http://www.discogs.com/artist/125246
TO: https://www.discogs.com/artist/125246-Nirvana



It seems this can be fixed by using the tip from  https://stackoverflow.com/questions/64416180/requests-get-not-working-with-certain-urls
This mimics a browser.... pretending our call is a web browser the request is no longer blocked
Tested and works with both versions of the URL (see below)

![image](https://user-images.githubusercontent.com/43116506/117429813-52a00d80-af1f-11eb-8d7b-1a742101514f.png)

**Comment by Err0neus** [comment]
question asked on Discogs form as well, before finding the workaround
https://www.discogs.com/forum/thread/871273

**Comment by Err0neus** [comment]
FALSE ALARM!!!
it doesn't really work  
what is actually returned is just the HTML code of this: 
![image](https://user-images.githubusercontent.com/43116506/117431021-a3643600-af20-11eb-91cb-a512e0cdd80a.png)

back to square one

**Comment by Err0neus** [comment]
CURL returns the correct content though... (when using the https version) perhaps there's a way to execute CURL from python?

**Comment by Err0neus** [comment]
Reply on DISCOGS: likely not going away, use the APIs (https://www.discogs.com/developers).

Similar issue discussed here: https://stackoverflow.com/questions/49087990/python-request-being-blocked-by-cloudflare 
A workaround suggests to use this https://pypi.org/project/cfscrape/ 
Cons:
- couldn't make it work
- currently 86 issues open (see on github https://github.com/Anorov/cloudflare-scrape/issues) and seems dead!


Can we revisit the APIs?

**Comment by Err0neus** [comment]
@Chitra0790 adding you back to this ticket as I may need your help testing the APIs.
As the REQUESTS route does not seem to be plausible without excessive workarounds, I'd like to evaluate in detail what we can and cannot get using the APIs.

**Comment by Err0neus** [comment]
let's try the **https://www.musicstack.com/** instead... 
seems good

Remember ampersands, i.e. Siouxsie+%2526+The+Banshees, nick+cave+%2526+the+bad+seeds
Artist name from DISCOGS.

**Comment by Err0neus** [comment]
replied to a thread on DISCOGS forum regarding the API way to get the "albums"

https://www.discogs.com/forum/thread/873283

**Comment by Err0neus** [comment]
just for the record... it is actually possible to get to the list of albums using Discogs APIs

Steps:
1) get the artist ID
2) get the list of artists releases (/artists/{artist_id}/releases)
3) for every release, identify the MASTER releases (where TYPE = 'master')
4) for every MASTER, get its main release ID (MAIN_RELEASE attribute)
5) use the main release ID to get the release details (/releases/{release_id})
6) then what we're looking for is any release where "Album" is in the list returned under the FORMATS attribute.

This way we would pretty much the same content as looking at the Artists' page "Albums" list.

few caveats:
- pagination -> the API calls would need to ensure we pull/process all the pages of the response
- API calls limitations -> would need to calibrate how many calls we do per minute/second to avoid exceeding the quotas.

Otherwise it's pretty doable :D

**Comment by Err0neus** [comment]
so... the below code seems to work quite well. 
note the API calls are "unauthorized" and as such are limited to 25 per minute (thus the TIME.SLEEP(2.4) between calls to only call the API once every 2.4 seconds max).
if we figure out how to authorize the calls, then the rate is 60 per minute (and we can change to on per second, or TIME.SLEEP(2))
see details here>> https://www.discogs.com/developers#page:home,header:home-rate-limiting


code (using **getArtistID** from get_discogs.py, otherwise using just 'requests'):


### get discography
```
def get_discography(input_artist_name):
    # get Discogs artist ID based on input name
    input_artist_id = getArtistID(input_artist_name)[0]
    # start lists
    discogs_artist_id, artist_name = [], []
    album_year, album_name, discogs_release_id = [], [], []
    discogs_users_have, discogs_rating_avg, discogs_rating_count = [], [], []
    # get artist's releases
    response = requests.request("GET", url + f"/artists/{input_artist_id}/releases?per_page=50000")
    releases = json.loads(response.text)
    # for each release...
    for release in releases['releases']:
        # ...if the release is a master, and role is Main (as opposed to "appearance", "producer" etc)...
        if release['type'] == 'master' and release['role'] == 'Main': 
            # ...get the release details.
            release_id = release['main_release']
            response = requests.request("GET", url + f"/releases/{release_id}")
            time.sleep(2.4)
            release_data = json.loads(response.text)
            # define formats we want to exclude
            exclude_formats = ['Compilation', 'Reissue', 'Promo', 'Remastered']
            try: 
                # then if flagged as Album and not flagged as formats we want to exclude
                if ('Album' in release_data['formats'][0]['descriptions'] \
                and (
                    len(set(release_data['formats'][0]['descriptions'])) \
                    == \
                    len(set(release_data['formats'][0]['descriptions']) - set(exclude_formats))
                )) == True:
                    # populate album details
                    discogs_artist_id.append(input_artist_id)
                    artist_name.append(release['artist'])
                    album_year.append(release_data['year'])
                    album_name.append(release_data['title'])
                    discogs_release_id.append(release_id)
                    discogs_users_have.append(release_data['community']['have'])
                    discogs_rating_avg.append(release_data['community']['rating']['average'])
                    discogs_rating_count.append(release_data['community']['rating']['count'])
            # exceptions may occur if no correct response is received or the response does not contain the required fields
            except:
                continue
    # finally, create and return the data as a pandas dataframe
    output = pd.DataFrame({
        'discogs_artist_id' : discogs_artist_id,
        'artist_name' : artist_name,
        'album_year' : album_year,
        'album_name' : album_name,
        'discogs_release_id' : discogs_release_id,
        'discogs_users_have' : discogs_users_have,
        'discogs_rating_avg' : discogs_rating_avg,
        'discogs_rating_count' : discogs_rating_count
    })
    return output
```




examples of outputs:
![image](https://user-images.githubusercontent.com/43116506/119992022-00a05400-bfc2-11eb-8bd5-9498feed6cfc.png)

**Comment by Err0neus** [comment]
Nirvana actually comes back nicely too :)
much much better than the actual artisth page on Discogs

![image](https://user-images.githubusercontent.com/43116506/119995286-562a3000-bfc5-11eb-8ed0-a12ff85b1b0d.png)

**Comment by Err0neus** [comment]
Closing because the Scraping approach works again. (url change from http to https)
